MODULES := Base \
	Source \
	Core PHOASify \
	CPS CPSify \
	Closed CC \
	Flat Flatten \
	Asm Codegen \
	CSE RegAlloc \
	PHOASifyWf CPSifyWf CCWf \
	CSEWf \
	Compiler \
	Examples \
	PHOASifyCorrect CPSifyCorrect CCCorrect FlattenCorrect CodegenCorrect \
	CSECorrect RegAllocCorrect \
	CompilerCorrect

include ../Makefile.example
