ifndef ESCAPE
	ESCAPE := ../..
endif

ifdef IMPREDICATIVE
	COQARGS := -impredicative-set
endif

VS         := $(MODULES:%=%.v)

.PHONY: coq clean

coq: Makefile.coq
	make -f Makefile.coq

LTP := -R $(ESCAPE)/src/coq LambdaTamer

Makefile.coq: Makefile $(VS)
	coq_makefile $(VS) \
		COQC = "coqc $(COQARGS) $(LTP)" \
		COQDEP = "coqdep $(LTP)" \
		-o Makefile.coq

clean:: Makefile.coq
	make -f Makefile.coq clean
	rm -f Makefile.coq .depend
