.PHONY: all clean

all:
	make -C STLC
	make -C STLCPlus
	make -C PatMatch
	make -C SysF
	make -C Untyped
	make -C Compose

clean:
	make -C STLC clean
	make -C STLCPlus clean
	make -C PatMatch clean
	make -C SysF clean
	make -C Untyped clean
	make -C Compose clean
